### PR TITLE
Add support for one-eyed cows

### PR DESCRIPTION
**Pull request by MeggyCal**
Are you the new upstream? 

Well, if you are, we can add some new images which have appeared in the meantime.

### CODE REVIEW

**Comment by BlitzKraft** [comment]
There seems to be an issue - stegosaurus doesn't show any eyes at all. Same happens with the milk.cow too. It seems like it should have worked. Are there any additional that need to be taken to complete installation? 

I just adopted this, seeing there is not any current maintainers. I just wanted to add the random feature and did that.

**Comment by MeggyCal** [comment]
Ouch, sorry, I have overseen your comment. I will look into it... it should have worked.

**Comment by MeggyCal** [comment]
it works for me (on Debian stretch). But you have to trust me, I am unable to copy the image here (it would be really messy)

**Comment by BlitzKraft** [comment]
My bad. I had my `$COWPATH` wrong. I have this version as well as distro provided version and I mixed them up. 

It's working as intended. Thank you for the pull @MeggyCal . Merging.

**Pull request merged**
